### ISSUE TITLE
DataFrameの他言語との比較表が欲しい

### ISSUE THREAD

**Issue by chezou** [JuliaTokyo/julia-wakalang#1]
RとPython(Pandas)との比較表が欲しい

[Interpreted Languages: JavaScript, PHP, Python, Ruby (Sheet One) - Hyperpolyglot](http://hyperpolyglot.org/scripting) みたいなイメージ

**Comment by sorami** [comment]
その昔 [Comparing Julia and R’s Vocabularies](http://www.johnmyleswhite.com/notebook/2012/04/09/comparing-julia-and-rs-vocabularies/) というのをJohn Myles Whiteさんが書いてましたが、Python/Pandasじゃないし、大分古いですね...

公式ドキュメントには [Noteworthy Differences from other Languages](http://docs.julialang.org/en/latest/manual/noteworthy-differences/) がありますが、網羅的なものが欲しいですね～。

**Comment by chezou** [comment]
なるほどー。
結構、Pythonだと`.group`みたいに`.`でつなげていけば何かできそうな感じがするのですが、Juliaだとgrobalなところにmethodがいるから把握しづらいんですよね〜

**Comment by jiahao** [comment]
悪い日本語のことは、許してください。

スピード比較は、JuliaLang/julia#10428 を参照します。pandasとRのほうがDataframes.jlとBase.readdlm()よりです。pandasとRのread functionsがC言語に書きました。そして、garbage collectionや、type inferenceや色々のdynamic overheadがありません。Julia v0.4のgarbage collectorは改善を期待します。

**Comment by chezou** [comment]
@jiahao 良いissueを教えてくれてありがとうございます！

I think Julia's garbage collection is not so good, and I force gc before my benchmarking... :(

**Comment by chezou** [comment]
僕が欲しかったのは[DataFramesMeta.jl](https://github.com/JuliaStats/DataFramesMeta.jl)でした。
これで、`where`, `orderby`などSQLlikeなDataFrameの処理が出来そうです

**Comment by chezou** [comment]
パフォーマンスについては、 index周りがないのが辛いという話をJuliaTokyo #3の懇親会で @bicycle1885 さんに聞きました

**Comment by chezou** [comment]
pivot_tableは`unstack`を使えば出来そう
http://stackoverflow.com/questions/27874472/julia-dataframe-group-by-and-pivot-tables-functions

**Comment by jiahao** [comment]
@chezou [ob/gctune](https://github.com/JuliaLang/julia/tree/ob/gctune) branch を見て誘います。 @carnavalさんを討議しましたーhttps://github.com/JuliaLang/julia/issues/10428#issuecomment-95350382 

今は、readdlmはgarbage collectorの最悪ケースです。Array{Any} outputのケースは、たくさんのboxed objectsが生産しました。Each time the gc runs, there is enough garbage removed so that the gc wants to continue being aggressive, even though there are O(N) objects at time N。そしでは、実行時間はO(N^2)です。その branchに特殊なheuristicsがあります。
